<!-- 搜索模块 -->
<?php if (!$fields) return?>
<div class="bg-white padder-m">
  <form method="<?= $method ? : 'POST' ?>" action="<?= $action ?>">
    <div class="row">
      <?php
      foreach ($fields as $name => $search) {
        echo \Gini\Model\Widget::factory("widgets/search/{$search['type']}", [
            'name' => $name,
            'form' => $form,
            'search' => $search
        ]);
      }
      ?>
      <div class="col-md-4">
        <div class="input-group heighted">
          <button class="btn btn-sm btn-primary" type="submit"><?= T('搜索') ?></button>
          <a style="margin-left: 10px;" class="btn btn-sm btn-warning" href="<?= url() ?>"><?= T('重置') ?></a>
        </div><!-- /input-group -->
      </div>
      <div class="offset-md-8 col-md-4 text-right">
        <label><a href="equipment/add"><i class="fa fa-plus mx-1" aria-hidden="true"></i></a></label>
        <label><a href="equipment/export"><i class="fa fa-upload mx-1" aria-hidden="true"></i></a></label>
        <label><a href="equipment/print"><i class="fa fa-print mx-1" aria-hidden="true"></i></a></label>
      </div>
    </div>
  </form>
</div>
<!-- 筛选模块-->
