<div class="col-md-8 search_height">
  <div class="input-group heighted">
    <span class="input-group-addon"><?= $search['title'] ?></span>
    <div data-date-format="dd MM yyyy - HH:ii p">
      <input class="form-control form_datetime input-sm" id="start_time" type="text" placeholder="起始时间" name="<?= $name . '[]' ?>" 
      value="<?= H($search['value'][0]) ?>" style="font-size: 12px;" autocomplete="off">
    </div>
    <span class="input-group-addon"><i class="fa fa-clock-o" aria-hidden="true"></i></span>
    <div data-date-format="dd MM yyyy - HH:ii p">
      <input class="form-control form_datetime input-sm" type="text" id="end_time" placeholder="截止时间" 
      name="<?= $name ?>[]" value="<?= H($search['value'][1]) ?>" style="font-size: 12px;" autocomplete="off">
    </div>
  </div><!-- /input-group -->
</div>
<script>
  $('#start_time').datetimepicker();
  $('#end_time').datetimepicker();
</script>