<form class="bg-white" id='equipmentForm' method="post" role="form" 
        action="gini-ajax:ajax/equipment/save">
    <?php if ($fields) foreach ($fields as $name => $field) :
        $title = $field['title'];
        $type = $field['type'];
        $require = $field['require'];
        $val = $field['value'];
    ?>  
        <?php if ($type == 'hidden') : ?>
            <input type="hidden" name="<?=$name?>" value="<?=$val?>">
        <?php endif;?>
        <?php if ($type == 'text') : ?>
            <div class="form-group row form-field-row padder10">
                <label class="offset-md-2 col-md-2 col-form-label text-center"><?= $title ?></label>
                <div class="col-md-4">
                    <input type="text" name="<?= $name?>" value="<?=$val?>"class="form-control input-field"  placeholder="请填写<?= $title ?>">
                </div>
                <?php if ($require) : ?>
                <div class="col-sm-2">
                <span class="require">*<?=T('必填')?></span>
                </div>
                <?php endif; ?>
            </div>
        <?php endif;?>
        <?php if ($type == 'select') : ?>
            <div class="form-group row form-field-row">
                <label class="offset-md-2 col-md-2 col-form-label text-center"><?= $title ?></label>
                <div class="col-md-4 text-center">
                    <select class="form-control input-field" name="<?=$name?>">
                        <?php foreach ($field['options'] as $k => $v) :?>
                            <option name = "<?= $name?>" value="<?=$k?>" <?=$k==$val?'selected':''?>><?= $v ?></option>
                        <?php endforeach;?>
                    </select>
                </div>
                <?php if ($require) : ?>
                <div class="col-sm-2">
                    <span class="require">*<?=T('必填')?></span>
                </div>
                <?php endif; ?>
            </div>
        <?php endif;?>
        <?php if ($type == 'textarea') : ?>
            <div class="form-group row padder10">
                <label class="offset-md-2 col-md-2 col-form-label text-center"><?= $title?></label>
                <div class="col-md-4 text-center">
                    <textarea class="form-control" name="<?= $name?>" rows="3"><?=$val?></textarea>
                </div>
                <?php if ($require) : ?>
                    <div class="col-sm-2">
                        <span class="require">*<?=T('必填')?></span>
                    </div>
                <?php endif; ?>
            </div>
        <?php endif;?>
        <?php if ($type == 'radio') : ?>
            <div class="form-group row form-field-ro padder10">
                <label class="offset-md-2 col-md-2 col-form-label text-center"><?= $title?></label>
                <div class="col-md-4 text-left line_height40">
                    <?php foreach ($field['options'] as $key => $value) : ?>
                    <label class="padder_left10"><input type="radio"  value="<?= $key?>" <?=$key==$val?'checked':''?> name="<?= $name?>"><span class="padder_left10"><?= $value?><span></label>
                    <?php endforeach;?>
                </div>
            </div>
        <?php endif;?>
    <?php endforeach; ?>
</form>
<div class="form-group form-field-ro padder10">
        <div class="offset-md-4 col-md-4">
        <button id="saveButton" type="submit" form="equipmentForm" class="btn btn-primary"><?= T('保存')?></button>
        </div>
</div>
<script>

$('body').on('submit', 'form[action^="gini-ajax:"]', function (e) {
    if ($(this).data('delegated')) return false;

    e.preventDefault();

    var $form = $(this);

    $form.trigger('ajax-before');

    $.ajax({
        type: $form.attr('method') || "POST",
        url: $form.attr('action').substring(10),
        data: $form.serialize(),
        success: function (html) {
            if(html.indexOf('replace') != -1){
                alert('保存成功');
            }else{
                alert('保存失败');
            }
            $form.trigger('ajax-success', html);
            $('body').append(html).find('script[data-ajax]').remove();
        },
        complete: function () {
            $form.trigger('ajax-complete');
        }
    });

    return false;
});
</script>
