<div class="panel panel-default table-responsive">
<?php if ($_SESSION['alert']) : ?>
    <div class="alert alert-<?= $_SESSION['alert']['type'] ?> alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
        <?php
        echo $_SESSION['alert']['message'];
        unset($_SESSION['alert']);
        ?>
    </div>
<?php endif; ?>  
  <!-- 搜索模块 -->
  <nav class="nav nav-pills nav-justified bg-white padder-m m-b-sm">
      <a class="nav-link active" href="equipment"><?=T('仪器列表')?></a>
      <a class="nav-link" href="equipment"><?=T('仪器的使用记录')?></a>
      <a class="nav-link" href="equipment"><?=T('仪器的使用评分')?></a>
      <a class="nav-link" href="equipment"><?=T('黑名单')?></a>
  </nav>
  <?= $searchForm ?>      
  <ul class="nav nav-tabs">
      <li class="nav-item">
          <a class="nav-link active" href="equipment"><?=T('正常设备')?></a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="equipment"><?=T('故障设备')?></a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="equipment"><?=T('废弃设备')?></a>
      </li>
  </ul>
  <div class="table-container bg-white">
    <table class="table">
      <thead>
        <th><?= T('仪器名称') ?></th>
        <th><?= T('仪器英文名称') ?></th>
        <th><?= T('仪器型号') ?></th>
        <th><?= T('放置地点') ?></th>
        <th class="text-right"><?= T('操作') ?></th>
      </thead>
      <tbody>
        <?php
        if ($data) foreach ($data as $v) :
          $id = $v['id'];
          $name = $v['name'];
          $enName = $v['en_name'];
          $mode_no = $v['mode_no'];
          $location = $v['location'];
        ?>
        <tr>
          <td><?= H($name)?></td>
          <td><?= H($enName)?></td>
          <td><?= H($mode_no)?></td>
          <td><?= H($location)?></td>
          <td class="text-right">
            <a href="equipment/edit/<?=$id?>" class="btn btn-primary btn-sm" role="button" aria-disabled="true"><?= T('编辑')?></a>
            <a href="gini-ajax:ajax/equipment/delete/<?=$id?>" class="btn btn-secondary btn-sm delete" data="<?=$id?>" role="button" aria-disabled="true"><?= T('删除')?></a>
          </td>
        </tr>
        <?php endforeach;?>
      </tbody>
    </table>
  </div>
</div>
<?= $pagination ?>
