<div class="panel panel-default table-responsive">
  <!-- 搜索模块 -->
  <nav class="nav nav-pills nav-justified bg-white padder-m m-b-sm">
      <a class="nav-link active" href="#"><?=T('仪器列表')?></a>
      <a class="nav-link" href="#"><?=T('仪器的使用记录')?></a>
      <a class="nav-link" href="#"><?=T('仪器的使用评分')?></a>
      <a class="nav-link" href="#"><?=T('黑名单')?></a>
  </nav>
  <?= $searchForm ?>      
  <ul class="nav nav-tabs">
      <li class="nav-item">
          <a class="nav-link active" href="#"><?=T('正常设备')?></a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="#"><?=T('故障设备')?></a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="#"><?=T('废弃设备')?></a>
      </li>
  </ul>
  <div class="table-container bg-white">
    <table class="table">
      <thead>
        <th><?= T('仪器名称') ?></th>
        <th><?= T('仪器英文名称') ?></th>
        <th><?= T('仪器型号') ?></th>
        <th><?= T('放置地点') ?></th>
        <th><?= T('操作') ?></th>
      </thead>
      <tbody>
        <?php
        if ($data) foreach ($data as $v) :
          $id = $v['id'];
          $name = $v['name'];
          $enName = $v['en_name'];
          $mode_no = $v['mode_no'];
          $location = $v['location'];
        ?>
        <tr>
          <td><?= H($name)?></td>
          <td><?= H($enName)?></td>
          <td><?= H($mode_no)?></td>
          <td><?= H($location)?></td>
          <td>
            <a href="equipment/edit/<?=$id?>" class="btn btn-primary btn-sm" role="button" aria-disabled="true">编辑</a>
            <a href="gini-ajax:ajax/equipment/delete/<?=$id?>" class="btn btn-secondary btn-sm delete" data="<?=$id?>" role="button" aria-disabled="true">删除</a>
          </td>
        </tr>
        <?php endforeach;?>
      </tbody>
    </table>
  </div>
</div>
<?= $pagination ?>

<script>
$('body').on('click', 'a[href^="gini-ajax:"]', function (e) {
    var $link = $(this);

    e.preventDefault();

    $link.trigger('ajax-before');

    $.ajax({
        type: "GET",
        url: $link.attr('href').substring(10),
        success: function(html) {
            if(html.indexOf('replace') != -1){
                alert('保存成功');
            }else{
                alert('保存失败');
            }
            $link.trigger('ajax-success', html);
            $('body').append(html).find('script[data-ajax]').remove();
        },
        complete: function() {
            $link.trigger('ajax-complete');
        }
    });

    return false;
});

</script>
