<div class="d-flex flex-row-reverse bg-white">
  <div class="p-2"><i class="fa fa-power-off"></i></div>
  <div class="p-2"><i class="fa fa-cog"></i> |</div>
  <div class="p-2"><i class="fa fa-question-circle-o"></i> |</div>
  <div class="p-2"><i class="fa fa-user-o"></i> <?=T('个人中心')?> |</div>
  <div class="p-2"><i class="fa fa-user-md"></i> <?=T('客服400-017-5664')?> |</div>
</div>

 
					
					 
					 
					