<div class="wrapper top">
    <label class="offset-md-1 col-md-3 no-wrapper">
        <div class="font-12 bg-color-white color-black text-center">help</div>
        <div class="font-12 text-center">lonovo</div>
    </label>
    <label class="col-md-4 no-wrapper font-24 font-blod">LIMS</label>
    <label class="col-md-3 no-wrapper font-12 text-left position">CF+</label>
</div>
<div class="user-panel">
    <div class="float-left image">
        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEEAAABBCAIAAAABlV4SAAAABnRSTlMAAAAAAABupgeRAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAl0lEQVRoge3YwQmAMBAFUSMWYCmWYqmWYimWYAf6hajDMu8cJEM8LNuGzDov4cm+tmO/PTN+cI+32cBgA4MNDDYw2MBQoaH9Ncx1VOEdbGCwgcEGBhsYbGCwgaGF5/LxNtku9v1ahXewgcEGBhsYbGCwgWGC7/mS6z3YVSbjV1/h3Sr8SzYw2MBgA4MNDDYwVGiQJEnStROvQQ6pd2sGNwAAAABJRU5ErkJggg==" class="img-circle" alt="User Image">
    </div>
    <div class="float-left info">
        <p>技术支持</p>
        <a href="#">南开大仪平台</a>
    </div>
</div>
<div class="user-info">
    <p>您课程组的仪器经费</p>
    <p>拖欠：￥194783.06</p>
    <p>余额：￥0</p>
</div>
<div class="panel-group" id="accordion">
    <div class="panel panel-default">
        <div class="panel-heading padding-menu" data-toggle="collapse" data-parent="#accordion"
                    href="#collapseOne">
            <h4 class="panel-title">
                <a>
                    <?= T('仪器模块') ?>
                    <i class="fa fa-angle-down float-right" aria-hidden="true"></i>
                </a>
            </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse show">
            <div class="panel-body">
                <a class="silder-color" href="equipment"><i class="fa fa-tasks" aria-hidden="true"></i><?= T('仪器目录')?></a>
            </div>
            <div class="panel-body">
                <i class="fa fa-tasks" aria-hidden="true"></i> <?= T('其他功能')?>
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading padding-menu" data-toggle="collapse" data-parent="#accordion"
                    href="#collapseTwo">
            <h4 class="panel-title">
                <a>
                    <?= T('统计模块')?>
                    <i class="fa fa-angle-right float-right" aria-hidden="true"></i>
                </a>
            </h4>
        </div>
        <div id="collapseTwo" class="panel-collapse collapse">
            <div class="panel-body">
                <i class="fa fa-tasks" aria-hidden="true"></i> <?= T('统计分析')?>
            </div>
            <div class="panel-body">
                <i class="fa fa-tasks" aria-hidden="true"></i> <?= T('报表功能')?>
            </div>
        </div>
    </div>
</div>
